### ISSUE TITLE
deleting lines with `dd` leaves behind a `d`

### ISSUE THREAD

**Issue by ssfrr** [bronson/vim-mode-next#1]
Not sure which PR caused this but when I use vim-mode-next , deleting a line using `dd` does delete the line but leaves the character `d` on what used to be the next line.

**Comment by bronson** [comment]
Wow, that's unexpected!  dd works perfectly for me on 0.54.11, Atom 1.0, OSX.

I just disabled all plugins other than vim-mode-next and played with it...  Didn't manage to reproduce it:

![bug3](https://cloud.githubusercontent.com/assets/1776/8514482/70d3c268-2345-11e5-9897-d22f78ebc290.gif)

Hopefully you can tell me you're doing something different?  Thanks for the report!

**Comment by ssfrr** [comment]
It looks like this is actually an issue with vim-mode, not with any of the PR's you merged in vim-mode-next, so we can close this here and hopefully handle it on the vim-mode side.
