### ISSUE TITLE
^f and ^b do not move cursor, only scroll the view

### ISSUE THREAD

**Issue by Mehuge** [bronson/vim-mode-next#11]
If vi(1) ctrl-f and ctrl-b should move the cursor forwards or backwards a 'page' and the view along with it.  In vim-mode-next only the view moves, the cursor remains where it is, rendering these commands somewhat useless.

This is on OSX don't know if the behaviour is the same on other platforms.

I believe the correct behaviour is for the cursor to move to the top (forward) or bottom (backward) of the displayed screen.

**Comment by Mehuge** [comment]
Seems the same is true for ^d and ^u, these also don't move the cursor.

From vim-mode.cson

```
  'ctrl-u': 'vim-mode:scroll-half-screen-up'
  'ctrl-b': 'vim-mode:scroll-full-screen-up'
  'pageup': 'vim-mode:scroll-full-screen-up'
  'ctrl-d': 'vim-mode:scroll-half-screen-down'
  'ctrl-f': 'vim-mode:scroll-full-screen-down'
  'pagedown': 'vim-mode:scroll-full-screen-down'
```

It isn't entirely obvious from http://vimhelp.appspot.com/usr_03.txt.html#03.7 that it should also move the cursor, but as a 30 year user of vi(1) and more recently vim(1) I noticed the lack of cursor movement immediately.

Also, it is not obvious from vim help text files, except for ^u and ^&d 

```
CTRL-D      Scroll window Downwards in the buffer.  The number of
            lines comes from the 'scroll' option (default: half a
            screen).  If [count] given, first set 'scroll' option
            to [count].  The cursor is moved the same number of
            lines down in the file (if possible; when lines wrap
            and when hitting the end of the file there may be a
            difference).  When the cursor is on the last line of
            the buffer nothing happens and a beep is produced.
            See also 'startofline' option.
            {difference from vi: Vim scrolls 'scroll' screen
            lines, instead of file lines; makes a difference when
            lines wrap}
```

But it doesn't go into the same level of detail for ^f and ^b so I guess it is debatable, but observed behaviour is that it moves the cursor as described in the bug report.  I have observed this on HPUX vi(1) and in vim(1) on linux/OSX (amongst many other versions in my time).

From HPUX vi(1) manual page:

```
      ^F         Scroll forward to display the window of text
                 following the current one.  A preceding count
                 specifies the number of windows to advance.  Two
                 lines of overlap are kept if possible.
                 (XPG4 only.) The current line is displayed and the
                 cursor is moved to the first nonblank character of
                 the current line or the first character if the line
                 is a blank line.
```

though its description of ^B is less informative.

Also: http://www.computerhope.com/unix/uvi.htm (Moving around)

**Comment by bronson** [comment]
You're absolutely right.  I'm pretty sure there's a bug opened for this in vim-mode's issue tracker but I'm not finding right now.

I've temporarily run out of time to keep vim-mode-next up-to-date.  Fixing the conflicts between the patches just took too much time.  If I get back into it, I'll use stgit to hopefully cut down on the manual labor involved with backing a patch back out and reordering patches to make conflicts appear sane.

You might give https://github.com/t9md/atom-vim-mode-plus a look.  I've been meaning to check it out for a few weeks now.  If you do, report back with how it goes.  :)

**Comment by bronson** [comment]
vim-mode-plus appears to handle this just like Vim.  Definitely worth the switch.

Closing since I've stopped working on vim-mode-next, vim-mode-plus is just too good.
