### ISSUE TITLE
Add Macros :)

### ISSUE THREAD

**Issue by caiocutrim** [bronson/vim-mode-next#12]
What you both think about macros?, the vim have a beatiful macros api. That recording keystrokes and repeat it. I want to do this, but I don't know where begins :(
I think this is really interesting and indispensable :)

**Comment by bronson** [comment]
Ideally you would start by finding out writing a package that adds this
functionality to Atom in general. The vim functionality then becomes a
matter of adding some key bindings.  (in theory...)

I picture an Atom macro package as something that makes it easy to record
and play back commands. No idea if one exists already, how hard could it
be? :)

**Comment by bronson** [comment]
Closing in favor of using vim-mode-plus (which doesn't have macros either, but that's where I'd add them)
