### ISSUE TITLE
Increment with `ctrl-A` doesn't work

### ISSUE THREAD

**Issue by ssfrr** [bronson/vim-mode-next#2]
placing the cursor over a number and pressing `ctrl-A` doesn't work in vim-mode-next, but does in vanilla vim-mode.

**Comment by bronson** [comment]
Wow, true.  Ctrl-x doesn't work either.  I'll see what's going on.  Thanks!

**Comment by bronson** [comment]
Nope, this is going to be harder to fix than I thought.  The problem is that vim-mode-next is receiving errors when trying to retrieve vim-mode's configuration settings.  Time to get more familiar with the configuration api...

**Comment by bronson** [comment]
More info...   If your ~/.atom/config.cson file contains:

``` cson
"*":
  ...
  "vim-mode": {}
  "vim-mode-next": {}
```

Then everything works.

However, if the vim-mode line is deleted, Atom returns undefined for all settings.  That means vim-mode.numberRegex is undefined, and ctrl-a/ctrl-x will fail.

I haven't figured out why this line gets deleted.

So, the awful workaround for now: make sure config.cson contains an empty vim-mode section.  Still looking for a better solution.

**Comment by bronson** [comment]
The fix is in 0.54.12.  Definitely repoen if you still see weirdness.
