### ISSUE TITLE
Implement Incremental Search

### ISSUE THREAD

**Issue by mrthebob** [bronson/vim-mode-next#5]
Implement incremental searching, such that a search is performed as the user types.

**Comment by bronson** [comment]
Yep, this would be a fantastic feature.  I expect it's coming, but it's probably a long way off.  Some more fundamental issues/reorgs need to get fixed first.

Have you seen https://atom.io/packages/lazy-motion?

**Comment by mrthebob** [comment]
This could work for now.  I still think it should be integrated in, but may
be a viable and good stop gap.  Thanks!

**Comment by mrthebob** [comment]
BTW, whoever this t9md guy is - I think he's a valuable contributor!

**Comment by bronson** [comment]
closing in favor of using vim-mode-plus, which supports incremental search quite well.

vim-mode-plus has gotten so good, there's not much point to vim-mode-next anymore...
