### ISSUE TITLE
Number row/special characters behave strangely in normal mode in Programmer Dvorak

### ISSUE THREAD

**Issue by mrthebob** [bronson/vim-mode-next#6]
When using Programmer Dvorak _in normal mode_, when I try to use the number row, it (mostly) tries to follow QWERTY mappings, oddly ($ and 0 don't work as if it were qwerty, while = works as if it were Prog. Dvorak, as it should, but it's the only one), so it's really strange what it's doing exactly.

Little confused.  This is the only app I seem to be having trouble with atm.  Things work as expected in normal mode in actual (g)vim.

**Comment by bronson** [comment]
Sounds just like all the hassles atom users with international keyboards have been having.  I've only seen the issues, never experienced it myself.

https://github.com/atom/atom-keymap/issues/37  (that's one, but there are lots of issues and lots of discussions)

And there's this, no idea...

https://atom.io/packages/keyboard-localization

**Comment by mrthebob** [comment]
Oh, sweet.  Given the layout builder, this might actually work.  I'll give
it a shot later and report back.

**Comment by mrthebob** [comment]
OK - I tried the keyboard localization, with no luck.  I can remap some keys, but it seems like there are a few different keys which are firing the same KeyDown event, even though they are firing different KeyPress events.  There's even one key that doesn't fire any event:  the period/raquo key. It's kind of odd.

The thing that I think is different between me and the other keymappers is this:  all keys operate as expected in insert mode in vim-mode-next.  For example, a $ is a $ in insert mode.  However, if I use Keypeek to tell me what's happening in normal mode, it seems to be firing `instead of $ while I'm in normal mode.  (This is just an example - there are plenty others.  Like` firing +.)  So, whatever's happening with the keys, it's happening when I'm in normal mode.  Without vim-mode-next on, all the keys operate as expected. 

Any thoughts?

Thanks!

**Comment by mrthebob** [comment]
Oh - also - the regular Dvorak layout works fine - it's just Programmer Dvorak that seems to have a problem.

**Comment by bronson** [comment]
Have you tried Programmer Dvorak in vim-mode-plus, with Atom 1.4?  A lot of improvements have landed that might make this work a lot better.

Closing because I've switched to vim-mode-plus for now.  It's really good.
